services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      # uses the DATABASE_URL  .env file
      DATABASE_URL: ${DATABASE_URL} 
      JWT_TOKEN_SECRET: ${JWT_TOKEN_SECRET}
      JWT_TOKEN_REFRESH_SECRET: ${JWT_TOKEN_REFRESH_SECRET}
      PORT: 8000
      # Google variables
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge