services:
  backend:
    build: .
    ports:
      - "8000:8000"
    # Use env_file to directly load variables from the .env file
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge